export const themas = {
    colors:{
        primary: "#1F48AA",
        secondary: "#FFFFFF",
        gray: "#D3D3D3",
        blue: "blue",
        azul_escuro: "#D69A01",
        azul_claro: "#34A3EE",
        black: "#000000",
        vinho: "#721c24",
        vinho_claro: "#D13535",
        rosa_muito_claro: "#f8d7da",
        rosa_claro: "#f5c6cb",
        rosa: "#FF6DD3",
        red: "red",
        verde_escuro: "#155724",
        verde_claro: "#d4edda",
        verde_medio: "#1B8F25",
        verde: "green",
        cinza_claro: "#e0e0e0",
        cinza: "gray",
        cinza_muito_claro: "#f5f5f5",
        chumbo: "#374151",
        chumbo_claro: "#4b5563",
        cinza_medio: "#9CA3AF",
        amarelo: "#D7AA0D",
        amarelo_muito_claro: "#FFFCF1",
        mostarda: "#FFBC14",
        mostarda_escuro: "#B38103",
        laranja: "#FF8B3E",
        laranja_forte: "#d35400",
        roxo: "#3A08C4",
    }
}